apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment-probe
  labels:
    app: demo-app
  annotations:
    kubernetes.io/change-cause: "Added probes"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: docker.io/library/k8s-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5

          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 10
            periodSeconds: 5