apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo-app
spec:
  containers:
    - name: demo-container
      image: docker.io/library/k8s-app:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 80